#Application
application-name: @artifactId@
application-description: @project.description@
application-version: @project.version@
contact-name: Juli√°n Camilo Vega Rocha
contact-email: ingjulianvega@gmail.com
contact-url: https://twitter.com/ingjulianvega

spring:
  application:
    name: @artifactId@
  profiles:
    active: local-discovery
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  #Cache
  cache:
    jcache:
      config: classpath:ehcache.xml
#Zipkin
  zipkin:
    baseUrl: http://localhost:9411/
  #config:
   # import: optional:configserver:http://localhost:8113
  #General configuration
server:
  port: 8094
  servlet:
    context-path: /asu/v1/administration-method
#Logging
#logging:
#  level:
#    root: DEBUG
#Exceptions
administration-method:
  api: @artifactId@
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://netflix:eureka@localhost:8761/eureka
